--- 
driver: 
  name: vagrant
platforms: 
  - 
    name: centos-7
provisioner: 
  deprecations_as_errors: true
  name: chef_zero
suites: 
  - 
    attributes: {}
    name: default
    run_list: 
      - "recipe[LinuxServer]"
verifier: 
  inspec_tests: 
    - 
      name: ssh-hardening
      url: "https://github.com/dev-sec/tests-ssh-hardening/archive/master.zip"
    - 
      git: "https://github.com/dev-sec/tests-os-hardening.git"
      name: os-hardening
