--- 
driver: 
  name: vagrant
platforms: 
  - 
    name: generic/rhel7
#  - name: amazonlinux
#    driver_config:
#      box: mvbcoding/awslinux
#  - name: centos-6
  - name: centos-7
#  - name: debian-7
#    run_list: apt::default
#  - name: debian-8
#    run_list: apt::default
#  - name: debian-9
#    run_list: apt::default
#  - name: fedora-26
#  - name: opensuse-leap-42
#  - name: ubuntu-14.04
#    run_list: apt::default
#  - name: ubuntu-16.04
#    run_list: apt::default

provisioner: 
  deprecations_as_errors: true
  name: chef_zero
suites: 
  - 
    attributes: {}
    name: default
    run_list: 
      - "recipe[LinuxServer]"
verifier: 
  name: inspec
